version: "3.7"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM= #optional
    hostname: digiraldo
    volumes:
      - ${STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${MEDIA}:/media
      - ${STORAGE}/tmp:/tmp
    restart: unless-stopped

version: "3.7"
services:
  emby:
    image: emby/embyserver_arm64v8
    container_name: emby
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STORAGE}:/config
      - ${MEDIA}/Series:/Series
      - ${MEDIA}/Peliculas:/Peliculas
      - ${MEDIA}/Cristiana-128:/Cristiana-128
      - ${MEDIA}/Gospel:/Gospel
      - ${MEDIA}/Documentales:/Documentales
      - ${MEDIA}:/media
    ports:
      - 8096:8096
      - 8920:8920 #optional
    restart: unless-stopped



version: "3.7"
services:
  emby:
    image: emby/embyserver_arm64v8
    container_name: emby
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STORAGE}:/config
      - ${MEDIA}/Series:/Series
      - ${MEDIA}/Peliculas:/Peliculas
      - ${MEDIA}/Cristiana-128:/Cristiana-128
      - ${MEDIA}/Gospel:/Gospel
      - ${MEDIA}/Documentales:/Documentales
      - ${MEDIA}:/media
    ports:
      - 8096:8096
      - 8920:8920 #optional
    restart: unless-stopped


version: "3.7"
services:
  transmission:
    image : jaymoulin/transmission:3.00-1.6.1
    container_name: transmission
    command: transmission-daemon -f -g /config
    volumes:
      - ./:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped
  
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=true 
    volumes:
      - ./jackett/config:/config
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/storage
    ports:
      - 9117:9117
    restart: unless-stopped
  
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - .config/sonarr:/config
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/storage
    ports:
      - 8989:8989
    restart: unless-stopped


version: "3.7"
services:
  flexget:
    image: wiserain/flexget:3.5
    container_name: flexget
    volumes:
      - ./:/config
      - ./custom-cont-init.d:/custom-cont-init.d
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/media
    ports:
      - 5050:5050
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=${PASFLEGE} # la puedes cambiar por la que quieras
    restart: unless-stopped

