version: "3.7"

services:

  samba:
    image: dperson/samba # no hay tag con versiones, solo latest
    container_name: samba
    restart: always
    command: '-u "${USERNAM};${PASSUSR}" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no" -s "externo;/externo;yes;no" -s "home;/home;yes;no"'
    stdin_open: true
    tty: true
    environment:
      - TZ=${TIZO}
    ports:
      - 139:139
      - 445:445
    volumes:
      - ${MEDIA}:/media
      - ${STORAGE}/torrents:/downloads
      - ${DISCEXT}:/externo
      - ./:/home
      
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${UPUID}
      - PGID=${GPGID}
      - TZ=${TIZO}
      - VERSION=docker
      - PLEX_CLAIM= #optional
    hostname: plex
    volumes:
      - ${STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${MEDIA}:/media
      - ${STORAGE}/tmp:/tmp
    restart: unless-stopped

  transmission:
    image : jaymoulin/transmission:3.00-1.6.1
    container_name: transmission
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped
  
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${UPUID}
      - PGID=${GPGID}
      - TZ=${TIZO}
    volumes:
      - ./jackett/config:/config
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/storage
    ports:
      - 9117:9117
    restart: unless-stopped
  
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${UPUID}
      - PGID=${GPGID}
      - TZ=${TIZO}
    volumes:
      - /sonarr/data:/config
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/storage
    ports:
      - 8989:8989
    restart: unless-stopped