version: "3.7"

services:

  samba:
    image: dperson/samba:rpi
    container_name: samba
    restart: always
    command: '-u "usernaa;Admin1234" -s "externo;/externo;yes;no"  -s "media;/media;yes;no" -s "downloads;/downloads;yes;no" -s "drive;/drive;yes;no" -s "config;/config;yes;no" -s "cache;/cache;yes;no" -s "tmp;/tmp;yes;no" -s "usernaa;/usernaa;yes;no" -s "complete;/complete;yes;yes" -s "incomplete;/incomplete;yes;no" -s "flexget-arm;/flexget-arm;yes;no"'
    stdin_open: true
    tty: true
    environment:
      #- PUID=usuarioid
      #- PGID=grupoid
      - TZ=timezona
    ports:
      - 139:139
      - 445:445
    volumes:
      - /usr/share/zoneinfo/timezona:/etc/localtime
      - discomontadoext:/externo
      - discomontadoext/compose:/usernaa
      - discomontadoext/media:/media
      - discomontadoext/compose/downloads:/downloads
      - discomontadoext/compose/downloads/complete:/complete
      - discomontadoext/compose/downloads/incomplete:/incomplete
      - discomontadoext/compose/drive:/drive
      - discomontadoext/compose/config:/config
      - discomontadoext/compose/cache:/cache
      - discomontadoext/compose/tmp:/tmp
      - discomontadoext/compose/flexget-arm:/flexget-arm

  plex:
    image: jaymoulin/plex:1.30.1.6562
    expose:
      - 32400
      - 33400
    # Descomentar si NO usas network_mode: "host"
    ports:
      - 32400:32400
      - 33400:33400
    environment:
      - PUID=usuarioid
      - PGID=grupoid
      - TZ=timezona
    volumes:
      - discomontadoext/compose/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - discomontadoext/media:/media
      - discomontadoext/compose/tmp:/tmp
    restart: unless-stopped
    # network_mode: "host" Solo funciona en Linux

  transmission:
    image : jaymoulin/transmission:3.00-1.6.1
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission:/config
      - discomontadoext/compose/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped

  flexget:
    image: wiserain/flexget:3.5
    volumes:
      - ./flexget:/config
      - ./flexget/custom-cont-init.d:/custom-cont-init.d
      - discomontadoext/compose/torrents:/downloads
      - discomontadoext/media:/storage
    ports:
      - 5050:5050
    environment:
      - PUID=usuarioid
      - PGID=grupoid
      - TZ=timezona
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=Nolateng0 # la puedes cambiar por la que quieras
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin:nightly
    container_name: jellyfin
    environment:
      - PUID=usuarioid
      - PGID=grupoid
      - TZ=timezona
      - UMASK_SET=022 #optional
    volumes:
      - discomontadoext/compose/config:/config
      - discomontadoext/media:/media
      - discomontadoext/compose/drive:/drive
      - discomontadoext/compose/srv/cache:/cache
      - discomontadoext/compose/srv/log:/log
      - discomontadoext/compose/srv/lib/metadata:/metadata
      - discomontadoext/compose/srv/lib/transcodes:/transcodes
    ports:
      - 8096:8096
      - 8920:8920 #optional
    restart: unless-stopped

  nginxpm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - ./mysql:/var/lib/mysql
