version: "3.7"

services:

  samba:
    image: dperson/samba:rpi
    container_name: samba
    restart: always
    command: '-u "usernaa;Admin1234" -s "externo;/externo;yes;no"  -s "media;/media;yes;no" -s "downloads;/downloads;yes;no" -s "drive;/drive;yes;no" -s "config;/config;yes;no" -s "cache;/cache;yes;no" -s "tmp;/tmp;yes;no" -s "usernaa;/usernaa;yes;no" -s "complete;/complete;yes;yes" -s "incomplete;/incomplete;yes;no" -s "flexget-arm;/flexget-arm;yes;no"'
    stdin_open: true
    tty: true
    environment:
      - PUID=usuarioid
      - PGID=grupoid
      - TZ=timezona
    ports:
      - 139:139
      - 445:445
    volumes:
      - /usr/share/zoneinfo/timezona:/etc/localtime
      - discomontadoext:/externo
      - discomontadoext/compose:/usernaa
      - discomontadoext/media:/media
      - discomontadoext/compose/downloads:/downloads
      - discomontadoext/compose/downloads/complete:/complete
      - discomontadoext/compose/downloads/incomplete:/incomplete
      - discomontadoext/compose/drive:/drive
      - discomontadoext/compose/config:/config
      - discomontadoext/compose/cache:/cache
      - discomontadoext/compose/tmp:/tmp
      - discomontadoext/compose/flexget-arm:/flexget-arm

  jellyfin:
    image: linuxserver/jellyfin:nightly
    container_name: jellyfin
    environment:
      - PUID=usuarioid
      - PGID=grupoid
      - TZ=timezona
      - UMASK_SET=022 #optional
    volumes:
      - discomontadoext/compose/config:/config
      - discomontadoext/media:/media
      - discomontadoext/compose/drive:/drive
      - discomontadoext/compose/srv/cache:/cache
      - discomontadoext/compose/srv/log:/log
      - discomontadoext/compose/srv/lib/metadata:/metadata
      - discomontadoext/compose/srv/lib/transcodes:/transcodes
    expose:
      - 8096
      - 8920
    # Descomentar si NO usas network_mode: "host"
    ports:
      - 8096:8096
      - 8920:8920 #optional
        restart: unless-stopped
    # network_mode: "host" Solo funciona en Linux

  transmission:
    image : jaymoulin/transmission:3.00-1.6.1
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission:/config
      - discomontadoext/compose/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped

  flexget:
    image: wiserain/flexget:3.5
    volumes:
      - ./flexget:/config
      - ./flexget/custom-cont-init.d:/custom-cont-init.d
      - discomontadoext/compose/torrents:/downloads
      - discomontadoext/media:/storage
    ports:
      - 5050:5050
    environment:
      - PUID=usuarioid
      - PGID=grupoid
      - TZ=timezona
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=Nolateng0 # la puedes cambiar por la que quieras
    restart: unless-stopped
