version: "3.7"

services:

  samba:
    image: dperson/samba # no hay tag con versiones, solo latest
    container_name: samba
    restart: always
    command: '-u "${USERNAM};${PASSUSR}" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no" -s "externo;/externo;yes;no"'
    stdin_open: true
    tty: true
    environment:
      - TZ=${TIZO}
    ports:
      - 139:139
      - 445:445
    volumes:
      - ${MEDIA}:/media
      - ${STORAGE}/torrents:/downloads
      - ${DISCEXT}:/externo

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${UPUID}
      - PGID=${GPGID}
      - TZ=${TIZO}
      - VERSION=docker
      - PLEX_CLAIM= #optional
    hostname: plex
    volumes:
      - ${STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${MEDIA}:/media
      - ${STORAGE}/tmp:/tmp
    restart: unless-stopped

  transmission:
    image : jaymoulin/transmission:3.00-1.6.1
    container_name: transmission
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped

  flexget:
    image: lscr.io/linuxserver/flexget:latest
    container_name: flexget
    command:
      - daemon
      - start
      - --autoreload-config
    volumes:
      - ./flexget:/config
      - ./flexget/custom-cont-init.d:/custom-cont-init.d
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/media
    ports:
      - 5050:5050
    environment:
      - PUID=${UPUID}
      - PGID=${GPGID}
      - TZ=${TIZO}
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=d1g1r4ld0_g0r0b3t4 # la puedes cambiar por la que quieras
    restart: unless-stopped