web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

tasks:
  eztvrss:
    rss: https://eztv.ag/ezrss.xml
    download: /data
    series:
      - See
      - Echo

schedules: no





tasks:
  showrss:
    rss: https://showrss.info/user/281965.rss?magnets=true&namespaces=true&name=null&quality=null&re=null
    download: /data
    series:
      - See
      - Echo



web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

tasks:
  showrss:
    rss: https://showrss.info/user/281965.rss?magnets=true&namespaces=true&name=null&quality=null&re=null
    download: /data
    series:
      - See
      - Echo

    transmission:
      host: localhost
      port: 9091
      username: casaos
      password: casaos
      path: ~/Descargas

schedules: no



web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

tasks:
  showrss:
    rss: https://showrss.info/user/281965.rss?magnets=true&namespaces=true&name=null&quality=null&re=null
    series:
      - See
      - Echo

    transmission:
      host: transmission
      port: 9091
      username: admin
      password: "123456"
      path: /downloads/complete

schedules: no