web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

tasks:
  eztvrss:
    rss: ttps://eztv.ag/ezrss.xml
    download: /downloads/complete
    series:
      - See
      - Halo
      - Echo

schedules: no
