web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

tasks:
  eztvrss:
    rss: ttps://eztv.ag/ezrss.xml
    download: /data
    series:
        settings:
        tv:
        exact: yes
        propers: 12 hours
        quality: 720p
      - See
      - Halo
      - Echo
      - Percy Jackson y los dioses del Olimpo
    regexp:
      reject:
        - x265: { from: title }
    transmission:
      host: transmission
      port: 9091
      username: admin
      password: "123456"
    

schedules: no